// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmvemrhhcbygpycnajvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdmVtcmhoY2J5Z3B5Y25hanZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzUyOTEsImV4cCI6MjA3MTY1MTI5MX0.STZF15PP-byK8H3WnQ8XAiRAO7X6T9u5yj6vOUHBq3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});